/**
 * RoboForge RHP1 firmware — STM32 (Keil MDK) reference template, v1
 * ------------------------------------------------------------------
 * Target: any STM32 with USART (tested pattern: STM32F103/STM32F4 HAL)
 * Keil usage: create an MDK project for your board, add stm32fxxx_hal
 * drivers, drop this as main.c, implement the three chassis hooks below.
 * Protocol: firmware/PROTOCOL.md — JSON lines at 115200 8N1.
 *
 * The PC-side RoboForge brain does NOT run on the MCU: this firmware is
 * the "body" — 100 Hz control loop, velocity ramping, watchdog, odometry.
 */

#include "main.h"        /* generated by STM32CubeMX for your board     */
#include <string.h>
#include <math.h>
#include <stdlib.h>

/* ===== chassis hooks — implement for your robot ===== */
static void DriveWheels(float v_l, float v_r) { (void)v_l; (void)v_r; }
static void Gripper(int close, const char *name) { (void)close; (void)name; }
static void ReadOdometry(float *x, float *y, float *th_deg)
{
    static float px = 0, py = 0, pth = 0;
    static uint32_t t0 = 0;
    extern float g_cmd_v, g_cmd_w_deg;
    uint32_t now = HAL_GetTick();
    float dt = (t0 ? (now - t0) : 10) / 1000.0f; t0 = now;
    px += g_cmd_v * cosf(pth) * dt;
    py += g_cmd_v * sinf(pth) * dt;
    pth += g_cmd_w_deg * 3.1415926f / 180.0f * dt;
    *x = px; *y = py; *th_deg = pth * 180.0f / 3.1415926f;
}
/* ===================================================== */

float g_cmd_v = 0.0f, g_cmd_w_deg = 0.0f;
static uint32_t last_cmd_tick = 0;

extern UART_HandleTypeDef huart1;   /* CubeMX-generated */

static int uart_getline(char *buf, int maxlen)
{
    static int n = 0;
    uint8_t ch;
    while (HAL_UART_Receive(&huart1, &ch, 1, 2) == HAL_OK) {
        if (ch == '\n') { buf[n] = 0; int len = n; n = 0; return len; }
        if (n < maxlen - 1) buf[n++] = (char)ch;
    }
    return 0;
}

static void uart_send(const char *s)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)s, (uint16_t)strlen(s), 100);
}

static void reply(const char *fmt, ...)
{
    char out[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(out, sizeof(out), fmt, ap);
    va_end(ap);
    uart_send(out);
    uart_send("\n");
}

static void handle_line(const char *line)
{
    last_cmd_tick = HAL_GetTick();
    /* Minimal JSON field scan; pull in cJSON for production use. */
    if (strstr(line, "\"ping\"")) {
        reply("{\"ok\":true,\"pong\":\"RHP1\"}");
    } else if (strstr(line, "\"pose\"")) {
        float x, y, th;
        ReadOdometry(&x, &y, &th);
        reply("{\"ok\":true,\"pose\":{\"x\":%.3f,\"y\":%.3f,\"theta_deg\":%.1f}}", x, y, th);
    } else if (strstr(line, "\"vel\"")) {
        const char *l = strstr(line, "\"l\":");
        const char *a = strstr(line, "\"a\":");
        g_cmd_v = l ? strtof(l + 4, NULL) : 0;
        g_cmd_w_deg = a ? strtof(a + 3, NULL) : 0;
        if (g_cmd_v > 1.5f) g_cmd_v = 1.5f;   /* hard clamp: firmware owns limits */
        if (g_cmd_v < -1.5f) g_cmd_v = -1.5f;
        if (g_cmd_w_deg > 60.0f) g_cmd_w_deg = 60.0f;
        if (g_cmd_w_deg < -60.0f) g_cmd_w_deg = -60.0f;
        reply("{\"ok\":true}");
    } else if (strstr(line, "\"stop\"")) {
        g_cmd_v = 0; g_cmd_w_deg = 0;
        reply("{\"ok\":true}");
    } else if (strstr(line, "\"grab\"")) {
        Gripper(1, "");  reply("{\"ok\":true,\"grabbed\":true}");
    } else if (strstr(line, "\"release\"")) {
        Gripper(0, "");  reply("{\"ok\":true}");
    } else if (strstr(line, "\"carrying\"")) {
        reply("{\"ok\":true,\"carrying\":null}");
    } else if (strstr(line, "\"objects\"")) {
        reply("{\"ok\":true,\"objects\":[]}");
    } else {
        reply("{\"ok\":false,\"error\":\"unknown cmd\"}");
    }
}

int roboforge_body_main(void)
{
    char line[512];
    uint32_t loop_t0 = HAL_GetTick();
    for (;;) {
        int len = uart_getline(line, sizeof(line));
        if (len > 0) handle_line(line);

        /* watchdog: brain silent 500 ms -> stop */
        if (HAL_GetTick() - last_cmd_tick > 500) { g_cmd_v = 0; g_cmd_w_deg = 0; }

        /* 100 Hz control loop with velocity ramping */
        if (HAL_GetTick() - loop_t0 >= 10) {
            loop_t0 = HAL_GetTick();
            static float cur_v = 0, cur_w = 0;
            float dv = g_cmd_v - cur_v;
            cur_v += (dv > 0.05f) ? 0.05f : (dv < -0.05f ? -0.05f : dv);
            float dw = g_cmd_w_deg - cur_w;
            cur_w += (dw > 3.0f) ? 3.0f : (dw < -3.0f ? -3.0f : dw);
            float w = cur_w * 3.1415926f / 180.0f;
            DriveWheels(cur_v - w * 0.10f, cur_v + w * 0.10f);
        }
    }
}
